#!/bin/sh

NAME=${PWD##*/}
TAG=${1:-"latest"}

echo "Building ${NAME}:${TAG}"
sleep 2

docker build -t aliem/${NAME}:${TAG} .
docker tag -f aliem/${NAME}:${TAG} aliem/${NAME}:latest
docker push aliem/${NAME}
