version: "2"
services:
    db:
        image: k0st/alpine-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
    adminer:
        build: .
        links:
            - db
        ports:
            - "8000:8080"
        environment:
            DB_HOST: "db"
            DB_USERNAME: "root"
            DB_PASSWORD: "toor"
